image: node:10.15.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm run build
          - docker build -t mit/mit-ui -t mit/mit-ui:${BITBUCKET_COMMIT} .
          - pipe: atlassian/aws-ecr-push-image:1.4.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${REGION}
              IMAGE_NAME: mit/mit-ui
              TAGS: ${BITBUCKET_COMMIT}
        services:
          - docker
    - step:
        name: Deploy
        deployment: Test
        script:
          - sed -i "s|{{image}}|$ECR/mit/mit-ui:${BITBUCKET_COMMIT}|g" deployment.yml
          - pipe: atlassian/aws-eks-kubectl-run:1.3.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${REGION}
              CLUSTER_NAME: ${CLUSTER_NAME}
              KUBECTL_COMMAND: "apply"
              RESOURCE_PATH: "deployment.yml"
              DEBUG: "true"